spring.application.name=cashdesk

server.port=8080
server.servlet.context-path=/api/v1

app.auth.api-key=f9Uie8nNf112hx8s

app.data.balances-file=src/main/resources/data/cash_balances.txt
app.data.transactions-file=src/main/resources/data/transactions.txt

logging.level.bg.fibank.cashdesk=INFO
